// <auto-generated />
using System;
using DatabaseLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseLayer.DbTables.Clubs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClubName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubName = "Pump it up",
                            Floor = 1,
                            Location = "Manchester"
                        },
                        new
                        {
                            Id = 2,
                            ClubName = "StudentCrew",
                            Floor = 1,
                            Location = "Huddersfield"
                        },
                        new
                        {
                            Id = 3,
                            ClubName = "Revolution",
                            Floor = 1,
                            Location = "Leeds"
                        },
                        new
                        {
                            Id = 4,
                            ClubName = "Viviera",
                            Floor = 1,
                            Location = "Keszthely"
                        });
                });

            modelBuilder.Entity("DatabaseLayer.DbTables.Dj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Dj");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = "4609ecd1-a827-4855-96b4-b5dc9d18e048"
                        },
                        new
                        {
                            Id = 2,
                            UserId = "8ba45c5e-3d41-46a5-b485-6cde638d12fd"
                        });
                });

            modelBuilder.Entity("DatabaseLayer.DbTables.DjSets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("DjId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformanceTimeEnds")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PerformanceTimeStarts")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("DjId");

                    b.ToTable("DjSets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubId = 1,
                            DjId = 1,
                            PerformanceTimeEnds = new DateTime(2025, 11, 7, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformanceTimeStarts = new DateTime(2025, 11, 6, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ClubId = 2,
                            DjId = 2,
                            PerformanceTimeEnds = new DateTime(2025, 11, 7, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformanceTimeStarts = new DateTime(2025, 11, 6, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ClubId = 3,
                            DjId = 1,
                            PerformanceTimeEnds = new DateTime(2025, 11, 5, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformanceTimeStarts = new DateTime(2025, 11, 5, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            ClubId = 4,
                            DjId = 2,
                            PerformanceTimeEnds = new DateTime(2025, 11, 5, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            PerformanceTimeStarts = new DateTime(2025, 11, 5, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DatabaseLayer.DbTables.Songs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("DjSetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("DjSetId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Basshunter",
                            ClubId = 1,
                            DjSetId = 1,
                            RequestedTime = new DateTime(2025, 11, 6, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Now You're Gone",
                            UserId = "0fc69c76-6089-43e0-864f-46f4c95f75b8"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Jennifer Lopez",
                            ClubId = 1,
                            DjSetId = 1,
                            RequestedTime = new DateTime(2025, 11, 6, 20, 11, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "On The Floor",
                            UserId = "21677737-93f9-41bd-a318-7027a2a480b4"
                        },
                        new
                        {
                            Id = 3,
                            Author = "David Guetta",
                            ClubId = 1,
                            DjSetId = 1,
                            RequestedTime = new DateTime(2025, 11, 6, 20, 26, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Titanium",
                            UserId = "0fc69c76-6089-43e0-864f-46f4c95f75b8"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Avicii",
                            ClubId = 1,
                            DjSetId = 1,
                            RequestedTime = new DateTime(2025, 11, 6, 20, 51, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Levels",
                            UserId = "21677737-93f9-41bd-a318-7027a2a480b4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Swedish House Mafia",
                            ClubId = 1,
                            DjSetId = 1,
                            RequestedTime = new DateTime(2025, 11, 6, 21, 16, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Don't You Worry Child",
                            UserId = "0fc69c76-6089-43e0-864f-46f4c95f75b8"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Calvin Harris",
                            ClubId = 1,
                            DjSetId = 1,
                            RequestedTime = new DateTime(2025, 11, 6, 21, 36, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Summer",
                            UserId = "21677737-93f9-41bd-a318-7027a2a480b4"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Rihanna",
                            ClubId = 1,
                            DjSetId = 1,
                            RequestedTime = new DateTime(2025, 11, 6, 22, 1, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "We Found Love",
                            UserId = "0fc69c76-6089-43e0-864f-46f4c95f75b8"
                        },
                        new
                        {
                            Id = 8,
                            Author = "LMFAO",
                            ClubId = 1,
                            DjSetId = 1,
                            RequestedTime = new DateTime(2025, 11, 6, 22, 26, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Party Rock Anthem",
                            UserId = "21677737-93f9-41bd-a318-7027a2a480b4"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Taio Cruz",
                            ClubId = 1,
                            DjSetId = 1,
                            RequestedTime = new DateTime(2025, 11, 6, 22, 46, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Dynamite",
                            UserId = "0fc69c76-6089-43e0-864f-46f4c95f75b8"
                        },
                        new
                        {
                            Id = 10,
                            Author = "The Weeknd",
                            ClubId = 1,
                            DjSetId = 1,
                            RequestedTime = new DateTime(2025, 11, 6, 23, 21, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Blinding Lights",
                            UserId = "21677737-93f9-41bd-a318-7027a2a480b4"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Pitbull",
                            ClubId = 2,
                            DjSetId = 2,
                            RequestedTime = new DateTime(2025, 11, 6, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "International Love",
                            UserId = "21677737-93f9-41bd-a318-7027a2a480b4"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Usher",
                            ClubId = 2,
                            DjSetId = 2,
                            RequestedTime = new DateTime(2025, 11, 6, 20, 16, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "DJ Got Us Fallin' In Love",
                            UserId = "0fc69c76-6089-43e0-864f-46f4c95f75b8"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Ne-Yo",
                            ClubId = 2,
                            DjSetId = 2,
                            RequestedTime = new DateTime(2025, 11, 6, 20, 41, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Closer",
                            UserId = "21677737-93f9-41bd-a318-7027a2a480b4"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Flo Rida",
                            ClubId = 2,
                            DjSetId = 2,
                            RequestedTime = new DateTime(2025, 11, 6, 21, 6, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Good Feeling",
                            UserId = "0fc69c76-6089-43e0-864f-46f4c95f75b8"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Lady Gaga",
                            ClubId = 2,
                            DjSetId = 2,
                            RequestedTime = new DateTime(2025, 11, 6, 21, 31, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Poker Face",
                            UserId = "21677737-93f9-41bd-a318-7027a2a480b4"
                        },
                        new
                        {
                            Id = 16,
                            Author = "Katy Perry",
                            ClubId = 2,
                            DjSetId = 2,
                            RequestedTime = new DateTime(2025, 11, 6, 21, 56, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Firework",
                            UserId = "0fc69c76-6089-43e0-864f-46f4c95f75b8"
                        },
                        new
                        {
                            Id = 17,
                            Author = "Black Eyed Peas",
                            ClubId = 2,
                            DjSetId = 2,
                            RequestedTime = new DateTime(2025, 11, 6, 22, 21, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "I Gotta Feeling",
                            UserId = "21677737-93f9-41bd-a318-7027a2a480b4"
                        },
                        new
                        {
                            Id = 18,
                            Author = "Adele",
                            ClubId = 2,
                            DjSetId = 2,
                            RequestedTime = new DateTime(2025, 11, 6, 22, 46, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 3,
                            Title = "Rolling in the Deep",
                            UserId = "0fc69c76-6089-43e0-864f-46f4c95f75b8"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Maroon 5",
                            ClubId = 2,
                            DjSetId = 2,
                            RequestedTime = new DateTime(2025, 11, 6, 23, 31, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Moves Like Jagger",
                            UserId = "21677737-93f9-41bd-a318-7027a2a480b4"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Coldplay",
                            ClubId = 2,
                            DjSetId = 2,
                            RequestedTime = new DateTime(2025, 11, 7, 0, 41, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 2,
                            Title = "Viva La Vida",
                            UserId = "0fc69c76-6089-43e0-864f-46f4c95f75b8"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Imagine Dragons",
                            ClubId = 3,
                            DjSetId = 3,
                            RequestedTime = new DateTime(2025, 11, 5, 20, 15, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Believer",
                            UserId = "0fc69c76-6089-43e0-864f-46f4c95f75b8"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Ed Sheeran",
                            ClubId = 3,
                            DjSetId = 3,
                            RequestedTime = new DateTime(2025, 11, 5, 20, 45, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Shape of You",
                            UserId = "21677737-93f9-41bd-a318-7027a2a480b4"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Marshmello",
                            ClubId = 3,
                            DjSetId = 3,
                            RequestedTime = new DateTime(2025, 11, 5, 21, 10, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Happier",
                            UserId = "0fc69c76-6089-43e0-864f-46f4c95f75b8"
                        },
                        new
                        {
                            Id = 24,
                            Author = "David Guetta",
                            ClubId = 3,
                            DjSetId = 3,
                            RequestedTime = new DateTime(2025, 11, 5, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Play Hard",
                            UserId = "21677737-93f9-41bd-a318-7027a2a480b4"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Avicii",
                            ClubId = 3,
                            DjSetId = 3,
                            RequestedTime = new DateTime(2025, 11, 5, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Wake Me Up",
                            UserId = "0fc69c76-6089-43e0-864f-46f4c95f75b8"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Calvin Harris",
                            ClubId = 3,
                            DjSetId = 3,
                            RequestedTime = new DateTime(2025, 11, 5, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Feel So Close",
                            UserId = "21677737-93f9-41bd-a318-7027a2a480b4"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Pitbull",
                            ClubId = 4,
                            DjSetId = 4,
                            RequestedTime = new DateTime(2025, 11, 5, 21, 15, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Give Me Everything",
                            UserId = "21677737-93f9-41bd-a318-7027a2a480b4"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Lady Gaga",
                            ClubId = 4,
                            DjSetId = 4,
                            RequestedTime = new DateTime(2025, 11, 5, 21, 45, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Bad Romance",
                            UserId = "0fc69c76-6089-43e0-864f-46f4c95f75b8"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Rihanna",
                            ClubId = 4,
                            DjSetId = 4,
                            RequestedTime = new DateTime(2025, 11, 5, 22, 10, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Diamonds",
                            UserId = "21677737-93f9-41bd-a318-7027a2a480b4"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Katy Perry",
                            ClubId = 4,
                            DjSetId = 4,
                            RequestedTime = new DateTime(2025, 11, 5, 22, 40, 0, 0, DateTimeKind.Unspecified),
                            StatusId = 1,
                            Title = "Teenage Dream",
                            UserId = "0fc69c76-6089-43e0-864f-46f4c95f75b8"
                        });
                });

            modelBuilder.Entity("DatabaseLayer.DbTables.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Accepted"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pending"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6f1b98cf-2a8a-4f59-826f-153b81d39120",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "d595d426-f92d-4aec-84a4-dcad31bd86e1",
                            Name = "DJ",
                            NormalizedName = "DJ"
                        },
                        new
                        {
                            Id = "c0fd7c02-4289-4cc3-8abf-2122919c1fc1",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8d35d26a-efbb-475b-a17d-7a5bdd38e0cb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd48c681-cff1-4b6c-8406-d00f34c99e36",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEGKwef27BwC4jACPYLeDjfDMZ52Df1khErJ8KlT2Ii6zL6cuat1kXXV1VVFtDthMCA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ee70639e-a5c5-4004-9dc7-91a548638d39",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "21677737-93f9-41bd-a318-7027a2a480b4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "325da8cc-52c8-4b9d-b592-abd574d43fb8",
                            Email = "user@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@EXAMPLE.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEIzbN2wTZjWvn58eRcf1kY8lUzo0uci2gtw/VBvApAvWKySbZ2xcHfSIKzLASbZcYQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "17aa6313-0910-4ae3-bec4-7479eb053bd9",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        },
                        new
                        {
                            Id = "0fc69c76-6089-43e0-864f-46f4c95f75b8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5618633f-6f6c-4a0d-be2b-fff4051033e1",
                            Email = "user2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEK+b/0tDVFYPlaxIAtCwPbwlFVy6mPWE/N8fXMGJHZ+xOhLdt7tm6CBDyKAwWwWp5w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1920ecbb-6f6d-4900-8495-148ccc69bba9",
                            TwoFactorEnabled = false,
                            UserName = "user2"
                        },
                        new
                        {
                            Id = "4609ecd1-a827-4855-96b4-b5dc9d18e048",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fe4bf0d4-a764-4ef4-a41b-cab577928892",
                            Email = "dj@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DJ@EXAMPLE.COM",
                            NormalizedUserName = "DJ",
                            PasswordHash = "AQAAAAIAAYagAAAAEBCs4mf+M3KRmqDyUHX48rDDZIQbyvcTyiYzm7DJkc5lwCC5ghmp/X074oLZVeyz2Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3003fe68-b5da-40db-b6f3-806431668a1e",
                            TwoFactorEnabled = false,
                            UserName = "dj"
                        },
                        new
                        {
                            Id = "8ba45c5e-3d41-46a5-b485-6cde638d12fd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3aa8b05b-4636-482f-831d-1310587931e5",
                            Email = "dj2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DJ2@EXAMPLE.COM",
                            NormalizedUserName = "DJ2",
                            PasswordHash = "AQAAAAIAAYagAAAAEJL6480F4BQFC+edkU6VlreONG8YLmmGfYzm4dQK+WyeiL6RQ93kT/TUnS7YszqRiA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2afa7ae4-6b60-470f-91c4-cb6fbef7478d",
                            TwoFactorEnabled = false,
                            UserName = "dj2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8d35d26a-efbb-475b-a17d-7a5bdd38e0cb",
                            RoleId = "6f1b98cf-2a8a-4f59-826f-153b81d39120"
                        },
                        new
                        {
                            UserId = "21677737-93f9-41bd-a318-7027a2a480b4",
                            RoleId = "c0fd7c02-4289-4cc3-8abf-2122919c1fc1"
                        },
                        new
                        {
                            UserId = "0fc69c76-6089-43e0-864f-46f4c95f75b8",
                            RoleId = "c0fd7c02-4289-4cc3-8abf-2122919c1fc1"
                        },
                        new
                        {
                            UserId = "4609ecd1-a827-4855-96b4-b5dc9d18e048",
                            RoleId = "d595d426-f92d-4aec-84a4-dcad31bd86e1"
                        },
                        new
                        {
                            UserId = "8ba45c5e-3d41-46a5-b485-6cde638d12fd",
                            RoleId = "d595d426-f92d-4aec-84a4-dcad31bd86e1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DatabaseLayer.DbTables.Dj", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithOne()
                        .HasForeignKey("DatabaseLayer.DbTables.Dj", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DatabaseLayer.DbTables.DjSets", b =>
                {
                    b.HasOne("DatabaseLayer.DbTables.Clubs", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.DbTables.Dj", "Dj")
                        .WithMany()
                        .HasForeignKey("DjId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Dj");
                });

            modelBuilder.Entity("DatabaseLayer.DbTables.Songs", b =>
                {
                    b.HasOne("DatabaseLayer.DbTables.Clubs", "Club")
                        .WithMany("Songs")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.DbTables.DjSets", "DjSets")
                        .WithMany()
                        .HasForeignKey("DjSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.DbTables.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("DjSets");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DatabaseLayer.DbTables.Clubs", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
